# Generated by Django 2.1.3 on 2018-12-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Department')),
                ('purchase_threshold', models.CharField(default='$0', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('birthday', models.DateField()),
                ('hire_date', models.DateField()),
                ('date_left', models.DateField()),
                ('status', models.CharField(choices=[('SA', 'Salary'), ('FT', 'Full Time'), ('PT', 'Part Time'), ('TM', 'Temporary')], default='PT', max_length=2)),
                ('rfid', models.CharField(max_length=255, unique=True)),
                ('hr_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('swag_group', models.CharField(choices=[(0, '0'), (30, '30'), (60, '60'), (90, '90'), (150, '150'), (1000, '1000')], default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Position')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Department')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Position'),
        ),
        migrations.AddField(
            model_name='department',
            name='admin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
